version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "11:00"
      timezone: "Europe/London"
    target-branch: "main"
