name: Build and Tests

on: [push]

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn # yarn cache files are stored in `~/.yarn` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install Packages
        run: yarn
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn run lint
  dependency-check:
    name: Run dependency check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn # yarn cache files are stored in `~/.yarn` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install Packages
        run: yarn
      - name: Dependency Check
        run: yarn run depcheck
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn # yarn cache files are stored in `~/.yarn` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install Packages
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
