name: Check version

on:
  pull_request:
    branches:
      - master

jobs:
  check-version:
    name: 'Check package version has changed'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 --tags origin
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@cdecatapult' # Defaults to the user or organization that owns the workflow file
      - name: Get Build Version
        id: get_version
        run: ./scripts/check-version.sh
        shell: bash
      - name: Check Version ⬆
        run: |
          exit $([[ "${{steps.get_version.outputs.is_new_version}}" = "true" ]] && echo 0 || echo 1)
